[package]
name = "name_generator"
version = "0.1.0"
authors = ["FirePlank <fireplankbusiness@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
names = "0.11.0"
rand = "0.7.3"